---
title: "lab05-Dui-Lee"
author: "Dui Lee"
date: "2018³â 9¿ù 26ÀÏ"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = '../images/')
```

##Filestructure and Shell Commands
```{r, eval=FALSE}
#Change your working directory to a location where you will store all the materials for this lab
$ cd Desktop/stat133

#Use mkdir to create a directory lab05 for the lab materials
$ mkdir lab05

#Use cd to change directory to (i.e. move inside) lab05
$ cd lab05

#Create other subdirectories: data, report, images
$ mkdir data report images

#Use ls to list the contents of lab05 and confirm that you have all the subdirectories.
$ ls

#Use touch to create an empty README.md text file
$ touch REAME.md

#Use a text editor (e.g. the one in RStudio) to open the README.md file, and then add a brief description of today¡¯s lab, using markdown syntax.
$ nano README.md

#Change directory to the data/ folder.
$ cd data

#Download the data file with the command curl, and the -O option (letter O)
$ curl -O https://raw.githubusercontent.com/ucb-stat133/stat133-fall-2018/master/data/nba2018-players.csv

#Use ls to confirm that the csv file is in data/
$ ls

#Use word count wc to count the lines of the csv file
$ wc nba2018-players.csv

#Take a peek at the first rows of the csv file with head
$ head nba2018-players.csv

#Take a peek at the last 5 rows of the csv file with tail
$ tail nba2018-players.csv -n 5

```


```{r}
library(dplyr)
library(ggplot2)
dat <- dat <- read.csv('../data/nba2018-players.csv', stringsAsFactors = FALSE)
```

##Basic "dplyr" verbs

###Filtering, slicing, and selecting

```{r}
#use slice() to subset the data by selecting the first 5 rows.
slice(dat, 1:5)

#use slice() to subset the data by selecting rows 10, 15, 20, ¡¦, 50.
slice(dat, seq(10,50,5))

#use slice() to subset the data by selecting the last 5 rows.
slice(dat, (length(dat$player)-4):length(dat$player))

#use filter() to subset those players with height less than 70 inches tall.
filter(dat, height < 70)

#use filter() to subset rows of Golden State Warriors (¡®GSW¡¯).
filter(dat, team == 'GSW')

#use filter() to subset rows of GSW centers (¡®C¡¯).
filter(dat, team == 'GSW' & position == 'C')

#use filter() and then select(), to subset rows of lakers (¡®LAL¡¯), and then display their names.
select(filter(dat, team == 'LAL'), player)

#use filter() and then select(), to display the name and salary, of GSW point guards
select(filter(dat, team == 'GSW' & position == 'PG'), player, salary)

#find how to select the name, age, and team, of players with more than 10 years of experience, making 10 million dollars or less.
select(filter(dat, experience > 10 & salary <= 10000000), player, age, team)

#find how to select the name, team, height, and weight, of rookie players, 20 years old, displaying only the first five occurrences (i.e. rows)
slice(select(filter(dat, age == 20), player, team, height, weight), 1:5)
```

###Adding new variables: mutate()

```{r}
# creating a small data frame step by step
gsw <- filter(dat, team == 'GSW')
gsw <- select(gsw, player, height, weight)
gsw <- slice(gsw, c(4, 8, 10, 14, 15))
gsw
```

```{r}
mutate(gsw, ht_wt = height/weight)
arrange(gsw, desc(height))
```

```{r}
#using the data frame gsw, add a new variable product with the product of height and weight.
mutate(gsw, product = height*weight)

#create a new data frame gsw3, by adding columns log_height and log_weight with the log transformations of height and weight.
gsw3 <- mutate(gsw, log_height = log(height), log_weight = log(weight))
gsw3

#use the original data frame to filter() and arrange() those players with height less than 71 inches tall, in increasing order.
arrange(filter(dat, height <= 71), height)

#display the name, team, and salary, of the top-5 highest paid players
slice(arrange(select(dat, player, team, salary), desc(salary)), 1:5)

#display the name, team, and points3, of the top 10 three-point players
slice(select(arrange(dat, desc(points3)), player, team, points3), 1:10)

#create a data frame gsw_mpg of GSW players, that contains variables for player name, experience, and min_per_game (minutes per game), sorted by min_per_game (in descending order)
gsw_mpg <- arrange(select(mutate(dat, min_per_game = minutes / games), player, experience, min_per_game), desc(min_per_game))
gsw_mpg

```

###Summarizing values with summarise()
```{r}
#use summarise() to get the largest height value.
summarise(dat, largest_height = max(height))

#use summarise() to get the standard deviation of points3.
summarise(dat, sd_of_points3 = sd(points3))

#use summarise() and group_by() to display the median of three-points, by team.
summarise(group_by(dat, team), points3_median = median(points3))

#display the average triple points by team, in ascending order, of the bottom-5 teams (worst 3pointer teams)
slice(
  arrange(
    summarise(
      group_by(dat, team), 
      points3_avg = mean(points)), 
    points3_avg), 
  1:5)

#obtain the mean and standard deviation of age, for Power Forwards, with 5 and 10 years (including) years of experience.
summarise(filter(dat, experience >= 5 & experience <= 10 & position == 'PF'), mean = mean(age), sd = sd(age))

```

##First contact with ggplot()
```{r heightweight scatter plot}
#Use the data frame gsw to make a scatterplot of height and weight.
ggplot(data = gsw, aes(x = height, y = weight) ) + geom_point()

```

```{r scatterplot with names}
#Find out how to make another scatterplot of height and weight, using geom_text() to display the names of the players.
ggplot(data = gsw, aes(x = height, y = weight) ) + geom_point() + geom_text(aes(label = player))
```

```{r warriors with name}
#Get a scatter plot of height and weight, for ALL the warriors, displaying their names with geom_label()
ggplot(data = filter(dat, team == 'GSW'), aes(x = height, y = weight)) + geom_label(aes(label = player))

```

```{r density plot}
#Get a density plot of salary (for all NBA players).
ggplot(data = dat, aes(salary)) + geom_density()

```

```{r points2 histogram}
#Get a histogram of points2 with binwidth of 50 (for all NBA players).
ggplot(data = dat, aes(points2)) + geom_histogram(binwidth = 50)
```

```{r barchart of position}
#Get a barchart of the position frequencies (for all NBA players).
ggplot(data = dat, aes(position)) + geom_bar()

```

```{r scatterplot of experiene and salary}
#Make a scatterplot of experience and salary of all Centers, and use geom_smooth() to add a regression line.
ggplot(data = filter(dat, position == 'C'), aes(x = experience, y = salary)) + geom_point() + geom_smooth(method=lm)

```

```{r same scatter plot but with loess line}
#Repeat the same scatterplot of experience and salary of all Centers, but now use geom_smooth() to add a loess line (i.e. smooth line)
ggplot(data = filter(dat, position == 'C'), aes(x = experience, y = salary)) + geom_point() + geom_smooth(method = loess)
```

###Faceting
```{r experience-salary scatterplot/position}
#Make scatterplots of experience and salary faceting by position
ggplot(data = dat, aes(x = experience, y = salary)) + geom_point() + facet_wrap(~ position)

```

```{r experience-salary scatterplot/team}
#Make scatterplots of experience and salary faceting by team
ggplot(data = dat, aes(x = experience, y = salary)) + geom_point() + facet_wrap(~ team)

```

```{r height-weight scatterplot/position}
#Make scatterplots of height and weight faceting by position
ggplot(data = dat, aes(x = height, y = weight)) + geom_point() + facet_wrap(~ position)
```

```{r height-weight scatterplot/position 2}
#Make scatterplots of height and weight, with a 2-dimensional density, geom_density2d(), faceting by position
ggplot(data = dat, aes(x = height, y = weight)) + geom_point() + facet_wrap(~ position) + geom_density2d()

```

```{r experience-salary scatter plot with theme}
#Make a scatterplot of experience and salary for the Warriors, but this time add a layer with theme_bw() to get a simpler background
ggplot(data = dat, aes(x = experience, y = salary)) + geom_point() + theme_bw()

```

```{r previous plot with new layer}
#Repeat any of the previous plots but now adding a leyer with another theme e.g. theme_minimal(), theme_dark(), theme_classic()
ggplot(data = dat, aes(x = experience, y = salary)) + geom_point() + theme_dark()
```

##More shell commands
```{r, eval=FALSE}
#Move inside the images/ directory of the lab.
$ cd ../images

#List the contents of this directory.
$ ls

#Now list the contents of the directory in long format.
$ ls -l

#How would you list the contents in long format, by time?
$ ls -l -t

#How would you list the contents displaying the results in reverse (alphabetical)? order
$ ls -l -r

#Without changing your current directory, create a directory copies at the parent level (i.e. lab05/).
$ mkdir ../copies

#Copy one of the PNG files to the copies folder.
$ cp 'warriors with name-1.png' ../copies

#Use the wildcard * to copy all the .png files in the directory copies.
$ cp *.png ../copies

#Change to the directory copies.
$ cd ../copies

#Use the command mv to rename some of your PNG files.
$ mv 'barchart of position-1.png' 'barchart_position.png'

#Change to the report/ directory.
$ cd ../report

#From within report/, find out how to rename the directory copies as copy-files.
$ mv ../copies ../copy-files

#From within report/, delete one or two PNG files in copy-files.
$ rm ../copy-files/'barchart_position.png'

#From within report/, find out how to delete the directory copy-files.
$ rm -r ../copy-files


```

