---
title: "lab09-Dui-Lee"
author: "Dui"
date: "2018³â 10¿ù 24ÀÏ"
output: html_document
---

#Part 2) Basics of String Manipulation

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```

```{r}
head(USArrests)
```

```{r}
states <- rownames(USArrests)
head(states)
```

##Number of Characters

```{r}
nchar(states)
```

###Case folding
```{r}
#strings to lower case
tolower(states)
```
```{r}
#strings to upper case
toupper(states)
```

```{r}
#can choose whether to upper or lower case
casefold(states, upper=TRUE)
```

###Length of States Names
```{r}
# number of charcaters
num_chars <- nchar(states)
char_freqs <- table(factor(num_chars))
char_freqs
barplot(char_freqs)
```

###Pasting strings

```{r}
paste(states[1:5], '=', num_chars[1:5])
```
```{r}
paste(states[1:5], collapse='')
```

###Permutation
```{r}
#Find the number of permutations that can be formed by using all the given letters in ALABAMA. For instance: "ALAMABA", "AMALABA", "AAAABML".
factorial(7)/factorial(4)
```

###Substrings

```{r}
substr(states, 1, 3)
```
```{r}
substr(states, nchar(states)-2, nchar(states))
```

```{r}
paste(substr(states, 1, 1), substr(states, nchar(states)-2, nchar(states)), sep='')
```

###Challenge

```{r}
# 4-char states
states[num_chars == 4]

# 10-char states
states[num_chars == 10]
```

```{r}
lst= list()
k = as.integer(levels(factor(num_chars)))

for (i in 1:length(k)) {
  if (k[i] %% 2 == 0) {
    lst[[i]] = toupper(states[num_chars == k[i]])
  }
  else {
    lst[[i]] = tolower(states[num_chars == k[i]])
  }
  

}

names(lst) <- paste(k, 'chars', sep = '-')
lst

```

##Converting from Fahrenheit Degrees

```{r}
to_celsius <- function(x = 1) {
  (x - 32) * (5/9)
}

to_kelvin <- function(x = 1) {
  (x + 459.67) * (5/9)
}

to_reaumur <- function(x = 1) {
  (x - 32) * (4/9)
}

to_rankine <- function(x = 1) {
  x + 459.67
}
```

##Your turn

```{r}
temp_convert <- function(x = 1, to = "celsius") {
  to = tolower(to)
  switch(to,
         "celsius" = to_celsius(x),
         "kelvin" = to_kelvin(x),
         "reaumur" = to_reaumur(x),
         "rankine" = to_rankine(x))
}

temp_convert(30, 'celsius')
```

```{r}
temp_convert(30, 'celsius')
temp_convert(30, 'Celsius')
temp_convert(30, 'CELSIUS')
```

###Names of files

```{r}
paste('file', 1:10, '.csv', sep = '')
paste0('file', 1:10, '.csv')

v = c()
for (i in 1:10){
  v[i] = paste0('file', i, '.csv')
}
v
```

```{r}
filenames = paste('file', 1:10, '.csv', sep = '')
filenames = paste0('dataset', substr(filenames, 5, nchar(filenames)))

filenames
```


##Using function cat()

```{r}
# name of output file
outfile <- "output.txt"

cat("---", file=outfile)
cat("\ntitle: \"Some title\"
author: \"Your name\"
date: \"today's date\"
output: html_document
---", file=outfile, append = TRUE)

cat("\n\n", file = outfile, append = TRUE)

# writing to 'outfile.txt'
cat("\nThis is the first line", file = outfile, append = TRUE)
# insert new line
cat("\n", file = outfile, append = TRUE)
cat("A 2nd line", file = "output.txt", append = TRUE)
# insert 2 new lines
cat("\n\n", file = outfile, append = TRUE)
cat("\nThe quick brown fox jumps over the lazy dog\n",
    file = outfile, append = TRUE)
```

##Valid Color Names

```{r}
# your is_color() function
#' @title is_color
#' @description returns whether provided name is a valid R color 
#' @param x a string
#' @return logical value
is_color <- function(x) {
  if (sum(colors()==x) > 0) {
    return(TRUE)
  }
  else {
    return(FALSE)
  }
}


# test it:
is_color('yellow')  # TRUE

is_color('blu')     # FALSE

is_color('turkuoise') # FALSE
```

```{r}
#' @title colplot
#' @description returns a random scatter plot with given color x if x is a valid R color
#' @param x a string
#' @return a scatter plot or a error message
colplot <- function(x) {
  if (is_color(x)) {
    plot(runif(10), runif(10), col = x)
  }
  else {
    stop("invalid color ", x)
  }
}

# this should plot
colplot('tomato')

# this stops with error message
colplot('tomate')
```

